# Generated by Django 4.2.30 on 2026-04-29 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('icon', models.CharField(default='bi-tag', help_text='Bootstrap icon class', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. USD, TZS, EUR', max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(default='$', max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='households_base', to='budget_app.currency')),
                ('members', models.ManyToManyField(related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_base', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('payee', models.CharField(blank=True, help_text='Merchant or source, e.g. "TotalEnergies"', max_length=120)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('recurring', 'Recurring'), ('request', 'Money Request'), ('import', 'Imported')], default='manual', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget_app.category')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='budget_app.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('name', models.CharField(help_text='e.g. "Rent", "Netflix"', max_length=120)),
                ('payee', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=15)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('auto_create', models.BooleanField(default=True, help_text='Automatically create transactions when due')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_app.category')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to='budget_app.household')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.CharField(help_text='What is this money for?', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=15)),
                ('response_note', models.TextField(blank=True, help_text='Approver/rejecter note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_to_approve', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Expense category once approved', null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_app.category')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('expense_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_expense_for', to='budget_app.transaction')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_requests', to='budget_app.household')),
                ('income_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_income_for', to='budget_app.transaction')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Liability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('liability_type', models.CharField(choices=[('loan', 'Loan'), ('mortgage', 'Mortgage'), ('credit_card', 'Credit Card'), ('other', 'Other')], default='loan', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual %', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='budget_app.household')),
            ],
            options={
                'verbose_name_plural': 'Liabilities',
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(help_text='Text to match against payee/description', max_length=200)),
                ('match_type', models.CharField(choices=[('contains', 'Contains'), ('equals', 'Equals'), ('starts_with', 'Starts with')], default='contains', max_length=15)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=10, help_text='Lower numbers run first')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='budget_app.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='budget_app.household')),
            ],
            options={
                'ordering': ['priority', 'pattern'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget_app.household'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('asset_type', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('investment', 'Investment'), ('property', 'Property/Real Estate'), ('vehicle', 'Vehicle'), ('other', 'Other')], default='bank', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='budget_app.household')),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('link_url', models.CharField(blank=True, max_length=300)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='budget_app.household')),
                ('user', models.ForeignKey(blank=True, help_text='If null, visible to all household members', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetWorthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(default=django.utils.timezone.now)),
                ('total_assets', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_worth', models.DecimalField(decimal_places=2, max_digits=14)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='budget_app.household')),
            ],
            options={
                'ordering': ['-snapshot_date'],
                'unique_together': {('household', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='budget_app.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='budget_app.currency')),
            ],
            options={
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('household', 'name', 'category_type')},
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month', models.DateField(help_text='First day of month')),
                ('alert_80_sent', models.BooleanField(default=False)),
                ('alert_100_sent', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='budget_app.category')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='budget_app.household')),
            ],
            options={
                'ordering': ['-month'],
                'unique_together': {('household', 'category', 'month')},
            },
        ),
    ]
