# Generated by Django 5.0.1 on 2026-05-24 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='When the asset was acquired', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(blank=True, help_text='Address, plot, or business location', max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Title deed, plate, or registration #', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='size',
            field=models.CharField(blank=True, help_text='e.g. 120 m², 0.5 acre, 3 bed / 2 bath', max_length=60),
        ),
        migrations.AddField(
            model_name='liability',
            name='due_date',
            field=models.DateField(blank=True, help_text='Final repayment date', null=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='lender',
            field=models.CharField(blank=True, help_text='Bank, person, or institution holding the debt', max_length=200),
        ),
        migrations.AddField(
            model_name='liability',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original loan / debt amount, if known', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='liability',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Account'), ('investment', 'Investment'), ('property', 'Property/Real Estate'), ('land', 'Land'), ('house', 'House'), ('business', 'Business'), ('vehicle', 'Vehicle'), ('other', 'Other')], default='bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='liability',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text='Current outstanding balance', max_digits=14),
        ),
        migrations.CreateModel(
            name='LiabilityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='budget_app.liability')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payment_for', to='budget_app.transaction')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
