# Generated by Django 5.0.1 on 2026-05-24 07:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_asset_acquisition_date_asset_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. "Q2 2026 Review"', max_length=160)),
                ('meeting_date', models.DateField(default=django.utils.timezone.now)),
                ('agenda', models.TextField(blank=True, help_text='What you plan to discuss')),
                ('minutes', models.TextField(blank=True, help_text='Summary / minutes of the meeting')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('held', 'Held'), ('cancelled', 'Cancelled')], default='planned', max_length=15)),
                ('income_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('expense_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('net_worth_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='budget_app.household')),
                ('participants', models.ManyToManyField(blank=True, related_name='meetings_attended', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-meeting_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgreementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, help_text='When this should be done by', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('progress', models.IntegerField(default=0, help_text='0 to 100')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_agreements', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='budget_app.meeting')),
            ],
            options={
                'ordering': ['status', '-priority', 'target_date'],
            },
        ),
    ]
