# Generated by Django 5.0.1 on 2026-05-24 09:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_goal_goalcontribution_project_transaction_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_name', models.CharField(help_text='Who borrowed from you', max_length=160)),
                ('debtor_contact', models.CharField(blank=True, help_text='Phone, email, etc. (optional)', max_length=200)),
                ('description', models.CharField(blank=True, help_text='What was the money for', max_length=255)),
                ('balance', models.DecimalField(decimal_places=2, help_text='Current outstanding amount', max_digits=14)),
                ('original_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Original amount lent (if different from balance)', max_digits=14, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual %', max_digits=5, null=True)),
                ('lent_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, help_text='When you expect repayment', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid in full'), ('written_off', 'Written off')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='budget_app.household')),
            ],
            options={
                'ordering': ['-balance'],
            },
        ),
        migrations.CreateModel(
            name='ReceivablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='budget_app.receivable')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivable_payment_for', to='budget_app.transaction')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
