# Generated by Django 5.2.15 on 2026-10-08 05:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_devicetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Mama Lishe Vikoba"', max_length=120)),
                ('group_type', models.CharField(choices=[('vikoba', 'Vikoba (savings & loans)'), ('mchezo', 'Mchezo (rotating pot)')], default='mchezo', max_length=10)),
                ('contribution_amount', models.DecimalField(decimal_places=2, help_text='What you pay in each time', max_digits=12)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=15)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('next_due_date', models.DateField(blank=True, help_text='The next agreed collection date. Cleared when the group ends.', null=True)),
                ('icon', models.CharField(default='bi-people-fill', help_text='Bootstrap icon class', max_length=50)),
                ('color', models.CharField(default='#6f42c1', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_groups', to='budget_app.household')),
            ],
            options={
                'ordering': ['-is_active', 'next_due_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='liability',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Set when this is a loan from a vikoba', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='budget_app.contributiongroup'),
        ),
        migrations.CreateModel(
            name='GroupContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='budget_app.contributiongroup')),
                ('money_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_contribution_for', to='budget_app.moneyrequest')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_contribution_for', to='budget_app.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('turn_order', models.PositiveIntegerField(default=1, help_text='1 = first to receive')),
                ('turn_date', models.DateField(blank=True, help_text='The date this member collects', null=True)),
                ('is_mine', models.BooleanField(default=False, help_text="This is our household's slot")),
                ('received_on', models.DateField(blank=True, help_text='Set once they have taken their turn', null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='budget_app.contributiongroup')),
            ],
            options={
                'ordering': ['turn_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='budget_app.currency')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='budget_app.contributiongroup')),
                ('member', models.ForeignKey(blank=True, help_text='The rotation slot this settles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='budget_app.groupmember')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_payout_for', to='budget_app.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
