import 'package:flutter/material.dart';

/// The web app stores Bootstrap Icons class names (`bi-cart3`) on categories,
/// goals and projects. Map the ones it seeds/suggests to Material icons.
const Map<String, IconData> biIcons = {
  'bi-tag': Icons.sell_outlined,
  'bi-cash-coin': Icons.payments_outlined,
  'bi-cash-stack': Icons.account_balance_wallet_outlined,
  'bi-laptop': Icons.laptop_mac,
  'bi-plus-circle': Icons.add_circle_outline,
  'bi-cart3': Icons.shopping_cart_outlined,
  'bi-cart': Icons.shopping_cart_outlined,
  'bi-house-door': Icons.home_outlined,
  'bi-house': Icons.home_outlined,
  'bi-lightning': Icons.bolt_outlined,
  'bi-fuel-pump': Icons.local_gas_station_outlined,
  'bi-bus-front': Icons.directions_bus_outlined,
  'bi-car-front': Icons.directions_car_outlined,
  'bi-cup-hot': Icons.local_cafe_outlined,
  'bi-film': Icons.movie_outlined,
  'bi-broadcast': Icons.subscriptions_outlined,
  'bi-heart-pulse': Icons.monitor_heart_outlined,
  'bi-piggy-bank': Icons.savings_outlined,
  'bi-bookmark-star': Icons.bookmark_outline,
  'bi-airplane': Icons.flight_outlined,
  'bi-gift': Icons.card_giftcard_outlined,
  'bi-book': Icons.menu_book_outlined,
  'bi-mortarboard': Icons.school_outlined,
  'bi-phone': Icons.smartphone_outlined,
  'bi-wifi': Icons.wifi,
  'bi-droplet': Icons.water_drop_outlined,
  'bi-basket': Icons.shopping_basket_outlined,
  'bi-bag': Icons.shopping_bag_outlined,
  'bi-tools': Icons.build_outlined,
  'bi-shield-check': Icons.verified_user_outlined,
  'bi-bank': Icons.account_balance_outlined,
  'bi-briefcase': Icons.work_outline,
  'bi-people': Icons.people_outline,
  'bi-person': Icons.person_outline,
  'bi-tree': Icons.park_outlined,
  'bi-hospital': Icons.local_hospital_outlined,
  'bi-capsule': Icons.medication_outlined,
  'bi-controller': Icons.sports_esports_outlined,
  'bi-music-note': Icons.music_note_outlined,
  'bi-graph-up': Icons.trending_up,
  'bi-credit-card': Icons.credit_card,
  'bi-wallet': Icons.account_balance_wallet_outlined,
  'bi-star': Icons.star_outline,
  'bi-trophy': Icons.emoji_events_outlined,
  'bi-hammer': Icons.handyman_outlined,
  'bi-flower1': Icons.local_florist_outlined,
  'bi-baby': Icons.child_friendly_outlined,
  'bi-paw': Icons.pets_outlined,
};

IconData biIcon(String? name) => biIcons[name] ?? Icons.sell_outlined;
